spring:
  datasource:
    username: root
    password: atguigu
    url: jdbc:mysql://192.168.243.102:3306/springboot?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    #指定数据库提供商
    database: mysql
    #打印SQL
    show-sql: true
    #是jpa层面对数据表生成策略的控制
    generate-ddl: true
    hibernate:
      #是jpa实现hibernate层面上对数据表生成策略的控制
      ddl-auto: update
      #指定命名策略
      naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
  main:
    allow-bean-definition-overriding: true
  redis:
    host: 192.168.243.102
    port: 6379

server:
  port: 8081
  servlet:
    context-path: /
logging:
  level:
    com.atguigu.dao: debug